services:
  fastzero_database:
    image: postgres
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - /home/ricardo/dev/fast_zero_db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  
  fastzero_app:
    image: fastzero_app
    network_mode: "host"
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fastzero_database
  
volumes:
  pgdata: